spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:auth-service}
    preferIpAddress: false