spring:
  cloud:
    config:
      uri: http://config-service:8888  # Или http://localhost:8888, если запускаете локально
      fail-fast: true  # Будет падать, если Config Server недоступен
      retry:
        initial-interval: 2000
        max-interval: 10000
        max-attempts: 5

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG