server:
  port: 8082
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/marketly_userservice_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  security:
    user:
          name: admin
          password: admin
          roles: ADMIN

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret-key: aXv7j3tR8kL9mQp2sV5y7x9A1zC4E7H0bW3cZ6u8oP1dF4rT5nJ9iK2lO0q
  access-token-expiration: 86400000
  refresh-token-expiration: 2592000000
  issuer: auth-service
  header: Authorization
  prefix: Bearer
  token-type: JWT


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs