spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update # Для разработки (в продакшене используйте validate)
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8082