spring:
  application:
    name: product-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
      # Настройки Redis
    data:
      redis:
        host: localhost
        port: 6379
        password: root
        database: 0
        timeout: 5000ms
        connect-timeout: 2000ms

    # Настройки кэширования
    cache:
      type: redis
      redis:
        time-to-live: 3600000    # 1 час в миллисекундах
        cache-null-values: false # Не кэшировать null значения
        use-key-prefix: true     # Использовать префиксы для ключей
        key-prefix: "cache:"     # Префикс для всех ключей кэша

    # Настройки Jackson (сериализация)
    jackson:
      serialization:
        fail-on-empty-beans: false
      deserialization:
        fail-on-unknown-properties: false

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tagsSorter: alpha
    operationsSorter: alpha
    doc-expansion: none
  info:
    title: Product Service API
    description: API для управления продуктами
    version: 1.0.0
    contact:
      name: Development Team
      email: dev@example.com