spring:
  application:
    name: cart-service  # Уникальное имя сервиса для Eureka
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: true  # Для Spring Data Redis Repositories

# Настройки Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Адрес Eureka Server
    register-with-eureka: true  # Регистрация в Eureka (по умолчанию true)
    fetch-registry: true        # Получение реестра сервисов (по умолчанию true)
  instance:
    prefer-ip-address: true    # Регистрация по IP вместо hostname
    lease-renewal-interval-in-seconds: 30  # Интервал отправки heartbeat

# Настройки Feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic


# Опционально: для более детального логирования Feign
logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
server:
  port: 8083