
# config:
#     import: "optional:configserver:http://localhost:8888"

server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF