server:
  port: ${EUREKA_PORT:8761}
spring:
  application:
    name: eureka-service
  spring:
    cloud:
      config:
        enabled: false
eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: ${EUREKA_HOST:eureka-service}
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: false
  client:
    fetch-registry: false
    register-with-eureka: false
    


management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    info:
      env:
        enabled: true