server:
  port: ${EUREKA_PORT:8761}
spring:
  application:
    name: eureka-service
  spring:
    cloud:
      config:
        enabled: false
eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always