server:
  port: ${CONFIG_PORT:8888}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
          default-label: ${SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL:main}
          clone-on-start: true
          force-pull: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-service:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG 