server:
  port: ${CONFIG_PORT:8888}

spring:
  application:
    name: config-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI:https://github.com/zhenyazzz/config-repo}
          default-label: ${SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL:main}
          clone-on-start: true
          force-pull: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/  
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: config-service 
    preferIpAddress: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    info:
      env:
        enabled: true

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG 